name: feta
on: pull_request

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: cat
        id: metadata-cat
        run: echo walter
          # The following properties are now available:
          #  - steps.metadata.outputs.dependency-names
          #  - steps.metadata.outputs.dependency-type
          #  - steps.metadata.outputs.update-type     